### ISSUE TITLE
Add support for TOML

### ISSUE THREAD

**Issue by wessven** [LucasVanHaaren/pelican-data-files#12]
TOML ([Tom's Obvious Minimal Language](https://toml.io/en/)) is a "config file format for humans". It is readable, unambiguous, and has a standardised format. It is also "designed to map unambiguously to a hash table". As such, it is a good choice for creating configuration or data files. Python 3.11 will release a TOML parser in the standard library.

**Comment by S1SYPHOS** [comment]
I know this is kinda unexpected, but since the open PR is .. well, old, I added a different approach to this .. 😃
