### ISSUE TITLE
Provide Support for data sub-directories

### ISSUE THREAD

**Issue by alexandry-augustin** [LucasVanHaaren/pelican-data-files#20]
It would be convenient to also support sub-directories similar to jekyl (https://jekyllrb.com/docs/datafiles/#subfolders).

For example: Files in the `content/data/subdir/` directory would be accessible via the `DATA_SUBDIR_` prefix variable in Jinja templates.

**Comment by LucasVanHaaren** [comment]
Hello @alexandry-augustin,

I totally agreed this will be a great feature to better organize data files !
Do you want to work on this feature implementation ?

**Comment by alexandry-augustin** [comment]
Hi @LucasVanHaaren,

Yes I can fix that, feel free to assign it me!

**Comment by alexandry-augustin** [comment]
Hi @LucasVanHaaren,

Yes I can fix that, feel free to assign it me!

**Comment by alexandry-augustin** [comment]
Pull request created. Let me know if you have any issues with it.

**Comment by LucasVanHaaren** [comment]
Hello @alexandry-augustin,

Thanks a lot for your work, I just reviewed your code, it seems great !
I will test it locally ASAP for further checks and if everything is good will merge it and release a new version

**Comment by LucasVanHaaren** [comment]
PR merged and released as 1.3.0 :tada: 

https://pypi.org/project/pelican-data-files/1.3.0/
